/*
 * CadastroCodigoBarras.java
 *
 * Created on 16 de Abril de 2007, 21:10
 */

package com.github.andrepenteado.contest.desktop;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import com.github.andrepenteado.contest.entity.CodigoBarras;
import com.github.andrepenteado.contest.entity.Produto;
import com.github.andrepenteado.contest.filters.ProdutoFilter;
import com.github.andrepenteado.contest.services.CadastroService;
import com.github.andrepenteado.core.ServicesFactory;
import com.github.andrepenteado.exception.ServiceValidationException;
import com.github.andrepenteado.util.ConfigHelper;
import com.github.andrepenteado.util.FunctionsHelper;
import com.github.andrepenteado.util.Log4jWrapper;
import com.github.andrepenteado.util.SwingHelper;

/**
 *
 * @author  Andre Penteado
 */
public class CadastroCodigoBarras extends javax.swing.JFrame {

    private static final long serialVersionUID = -1819015156799685153L;
    private Log4jWrapper log = new Log4jWrapper(CadastroCodigoBarras.class, Login.getUserLogin());
    private CadastroService cadastroService = null;
    private CodigoBarras codigoBarrasAtual = null;
    private List<CodigoBarras> listaEstoque = null;

    /** Creates new form CadastroCodigoBarras */
    public CadastroCodigoBarras() {
        try {
            if (Login.getUserLogin() == null)
                throw new Exception(ConfigHelper.get().getString("error.accessDenied"));
            cadastroService = (CadastroService)ServicesFactory.getInstance(CadastroService.class, new Object[] { Login.getUserLogin() });
            initComponents();
        }
        catch (Exception ex) {
            log.fatal("AÇÕES NÃO INSTANCIADAS: ".concat(CadastroCodigoBarras.class.getName()), ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), ConfigHelper.get().getString("error.general"), JOptionPane.ERROR_MESSAGE);
        }
    }

    public void limparCampos() {
        codigoBarrasAtual = null;
        listaEstoque = null;
        DefaultListModel dlm = new DefaultListModel();
        dlm.clear();
        lstCodigos.setModel(dlm);
        txtCodigoBarras.setText("");
        txtProduto.setText("");
        txtProduto.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoBarras = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        lblProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        btnIncluirCodigo = new javax.swing.JButton();
        scrCodigos = new javax.swing.JScrollPane();
        lstCodigos = new javax.swing.JList();
        btnExcluirCodigo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblCabecalho = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ConfigHelper.get().getString("sistema.nome") + " :: Códigos de Barras");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/logotipo.png")));
        setResizable(false);

        lblCodigoBarras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCodigoBarras.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigoBarras.setText("Código de Barras");

        txtCodigoBarras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirCodigo(evt);
            }
        });
        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarNumeroInteiro(evt);
            }
        });

        lblProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProduto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProduto.setText("Produto");

        txtProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        btnIncluirCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir_16x16.png"))); // NOI18N
        btnIncluirCodigo.setText("Incluir");
        btnIncluirCodigo.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnIncluirCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirCodigo(evt);
            }
        });
        btnIncluirCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lstCodigos.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lstCodigos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCodigos.setVisibleRowCount(7);
        lstCodigos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });
        scrCodigos.setViewportView(lstCodigos);

        btnExcluirCodigo.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnExcluirCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir_22x22.png"))); // NOI18N
        btnExcluirCodigo.setText("Excluir [Del]");
        btnExcluirCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCodigoActionPerformed(evt);
            }
        });
        btnExcluirCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_22x22.png"))); // NOI18N
        btnCancelar.setText("Cancelar [Esc]");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCabecalho.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        lblCabecalho.setForeground(java.awt.Color.blue);
        lblCabecalho.setText("Cadastro de Códigos de Barras");
        lblCabecalho.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.png"))); // NOI18N

        lblMensagem.setFont(new java.awt.Font("DejaVu Sans", 1, 10)); // NOI18N
        lblMensagem.setForeground(java.awt.Color.red);
        lblMensagem.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        org.jdesktop.layout.GroupLayout.TRAILING,
                        jPanel1Layout.createSequentialGroup().addContainerGap().add(
                                        jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblMensagem,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE).add(lblCabecalho,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)).addPreferredGap(
                                        org.jdesktop.layout.LayoutStyle.RELATED).add(lblLogotipo).addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblLogotipo,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE).add(
                        jPanel1Layout.createSequentialGroup().add(lblCabecalho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                                        lblMensagem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).add(
                        org.jdesktop.layout.GroupLayout.TRAILING,
                        layout.createSequentialGroup().addContainerGap(123, Short.MAX_VALUE).add(btnExcluirCodigo,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(btnCancelar).addContainerGap()).add(
                        layout.createSequentialGroup().addContainerGap().add(
                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                                                        org.jdesktop.layout.GroupLayout.TRAILING,
                                                        layout.createSequentialGroup().add(lblProduto).addPreferredGap(
                                                                        org.jdesktop.layout.LayoutStyle.RELATED).add(txtProduto,
                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)).add(
                                                        layout.createSequentialGroup().add(lblCodigoBarras).addPreferredGap(
                                                                        org.jdesktop.layout.LayoutStyle.RELATED).add(txtCodigoBarras,
                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                                                                                        btnIncluirCodigo,
                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85,
                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap()).add(
                        layout.createSequentialGroup().addContainerGap().add(scrCodigos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405,
                                        Short.MAX_VALUE).addContainerGap()));

        layout.linkSize(new java.awt.Component[] { lblCodigoBarras, lblProduto }, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] { btnCancelar, btnExcluirCodigo }, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        layout.createSequentialGroup().add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblProduto,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(txtProduto,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.RELATED).add(
                                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblCodigoBarras,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(btnIncluirCodigo,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(txtCodigoBarras,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.RELATED).add(scrCodigos,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE).addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.UNRELATED).add(
                                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(btnCancelar,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(btnExcluirCodigo))
                                        .addContainerGap()));

        layout.linkSize(new java.awt.Component[] { lblCodigoBarras, lblProduto, txtCodigoBarras, txtProduto },
                        org.jdesktop.layout.GroupLayout.VERTICAL);

        layout.linkSize(new java.awt.Component[] { btnCancelar, btnExcluirCodigo }, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCodigoActionPerformed
        try {
            if (listaEstoque == null || lstCodigos.getSelectedIndex() == -1)
                throw new ServiceValidationException(ConfigHelper.getProperty("error.notSelected", "Código de Barras"));

            CodigoBarras codigoBarras = listaEstoque.get(lstCodigos.getSelectedIndex());
            codigoBarras.excluir();
            popularListaCodigoBarras();
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.getProperty("info.deleteOk", "Código de Barras"));
        }
        catch (ServiceValidationException sve) {
            SwingHelper.exibeMensagemTemporaria(lblMensagem, sve.getMessage());
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }

        txtCodigoBarras.requestFocus();
        txtCodigoBarras.selectAll();
    }//GEN-LAST:event_btnExcluirCodigoActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        try {
            ProdutoFilter filter = new ProdutoFilter();
            filter.setDescricao(txtProduto.getText());
            List<Produto> lstProdutos = new ArrayList<Produto>(filter.executeFilter());

            PopupConsulta popup = new PopupConsulta(this, true, lstProdutos);
            popup.setVisible(true);
            Produto prodResult = (Produto)popup.getResult();
            prodResult.getCodigosBarras().size();
            popup.dispose();

            if (codigoBarrasAtual == null) {
                codigoBarrasAtual = new CodigoBarras();
                codigoBarrasAtual.setCodigoBarras(txtCodigoBarras.getText());
                codigoBarrasAtual.setProduto(prodResult);
            }

            popularListaCodigoBarras();
            txtProduto.setText(prodResult.getDescricao());
            txtCodigoBarras.requestFocus();
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void incluirCodigo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirCodigo
        try {
            String numeroCodigoBarras = txtCodigoBarras.getText();
            CodigoBarras codigoBarras = cadastroService.buscarCodigoBarrasPorNumero(numeroCodigoBarras);

            if (codigoBarras == null) {
                codigoBarras = new CodigoBarras();
                codigoBarras.setId(-1l);
            }
            else {
                throw new ServiceValidationException(ConfigHelper.getProperty("error.found", "Código de Barras"));
            }

            codigoBarras.setCodigoBarras(numeroCodigoBarras);
            codigoBarras.setProduto(codigoBarrasAtual.getProduto());
            codigoBarras.gravar();
            popularListaCodigoBarras();
        }
        catch (ServiceValidationException saie) {
            SwingHelper.exibeMensagemTemporaria(lblMensagem, saie.getMessage());
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }

        txtCodigoBarras.requestFocus();
        txtCodigoBarras.selectAll();
    }//GEN-LAST:event_incluirCodigo

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void getKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getKey
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ESCAPE) {
            if (txtProduto.isFocusOwner()) {
                btnCancelarActionPerformed(null);
            }
            else {
                limparCampos();
            }
        }
        else if (tecla == KeyEvent.VK_DELETE) {
            if (lstCodigos.isFocusOwner())
                btnExcluirCodigoActionPerformed(null);
            else if (lstCodigos.getModel().getSize() > 0) {
                lstCodigos.requestFocus();
                lstCodigos.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_getKey

    private void popularListaCodigoBarras() throws ServiceValidationException {
        listaEstoque = cadastroService.pesquisarCodigoBarrasPorProduto(codigoBarrasAtual.getProduto().getId());

        if (listaEstoque != null) {
            txtProduto.setText(codigoBarrasAtual.getProduto().getDescricao());
            DefaultListModel dlm = new DefaultListModel();
            for (int i = 0; i < listaEstoque.size(); i++) {
                CodigoBarras codigoBarras = listaEstoque.get(i);
                dlm.addElement(FunctionsHelper.fillSpacesLeft(codigoBarras.getCodigoBarras().trim(), 27));
            }
            lstCodigos.setModel(dlm);
        }
    }

    private void validarNumeroInteiro(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarNumeroInteiro
        SwingHelper.validarNumeroInteiro(evt);
    }//GEN-LAST:event_validarNumeroInteiro

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluirCodigo;
    private javax.swing.JButton btnIncluirCodigo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JList lstCodigos;
    private javax.swing.JScrollPane scrCodigos;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables
}