/*
 * Desktop.java
 *
 * Created on 29 de Março de 2007, 18:39
 */

package com.github.andrepenteado.contest.desktop;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;

import com.github.andrepenteado.util.ConfigHelper;
import com.github.andrepenteado.util.SwingHelper;

/**
 *
 * @author  Andre Penteado
 */
public class Desktop extends javax.swing.JFrame {

    private static final long serialVersionUID = -1802560862892211174L;
    private static AbrirCaixa abrirCaixa = null;
    private static FecharCaixa fecharCaixa = null;
    private static MovimentoCaixa movimentoCaixa = null;
    private static CadastroCodigoBarras cadastroCodigoBarras = null;
    private static TotalVendidoCaixa totalVendidoCaixa = null;

    /** Creates new form Desktop */
    public Desktop() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraFerramentasPrincipal = new javax.swing.JToolBar();
        btnBarraCadastroCodigosProdutos = new javax.swing.JButton();
        btnBarraAbrirCaixa = new javax.swing.JButton();
        btnBarraFecharCaixa = new javax.swing.JButton();
        btnBarraMovimentarCaixa = new javax.swing.JButton();
        btnBarraSair = new javax.swing.JButton();
        lblRodape = new javax.swing.JLabel();
        dskPrincipal = new javax.swing.JDesktopPane();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuSuperiorCaixa = new javax.swing.JMenu();
        menuCadastroCodigos = new javax.swing.JMenuItem();
        sep1 = new javax.swing.JSeparator();
        menuAbrirCaixa = new javax.swing.JMenuItem();
        menuFecharCaixa = new javax.swing.JMenuItem();
        sep2 = new javax.swing.JSeparator();
        menuMovimentarCaixa = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuTotalVendidoCaixa = new javax.swing.JMenuItem();
        menuSuperiorSair = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(ConfigHelper.get().getString("sistema.nome") + " :: Módulo PDV");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/logotipo.png")));

        barraFerramentasPrincipal.setFloatable(false);
        barraFerramentasPrincipal.setFocusable(false);
        barraFerramentasPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        btnBarraCadastroCodigosProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar_codigos_22x22.png"))); // NOI18N
        btnBarraCadastroCodigosProdutos.setToolTipText("Entrada de Códigos de Produtos");
        btnBarraCadastroCodigosProdutos.setFocusable(false);
        btnBarraCadastroCodigosProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCodigos(evt);
            }
        });
        btnBarraCadastroCodigosProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });
        barraFerramentasPrincipal.add(btnBarraCadastroCodigosProdutos);

        btnBarraAbrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abrir_caixa_22x22.png"))); // NOI18N
        btnBarraAbrirCaixa.setToolTipText("Abrir Caixa");
        btnBarraAbrirCaixa.setFocusable(false);
        btnBarraAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCaixa(evt);
            }
        });
        btnBarraAbrirCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });
        barraFerramentasPrincipal.add(btnBarraAbrirCaixa);

        btnBarraFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar_caixa_22x22.png"))); // NOI18N
        btnBarraFecharCaixa.setToolTipText("Fechar Caixa");
        btnBarraFecharCaixa.setFocusable(false);
        btnBarraFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharCaixa(evt);
            }
        });
        btnBarraFecharCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });
        barraFerramentasPrincipal.add(btnBarraFecharCaixa);

        btnBarraMovimentarCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/movimentar_caixa_22x22.png"))); // NOI18N
        btnBarraMovimentarCaixa.setToolTipText("Movimentar Caixa");
        btnBarraMovimentarCaixa.setFocusable(false);
        btnBarraMovimentarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movimentarCaixa(evt);
            }
        });
        btnBarraMovimentarCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });
        barraFerramentasPrincipal.add(btnBarraMovimentarCaixa);

        btnBarraSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair_22x22.png"))); // NOI18N
        btnBarraSair.setToolTipText("Sair");
        btnBarraSair.setFocusable(false);
        btnBarraSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair(evt);
            }
        });
        btnBarraSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });
        barraFerramentasPrincipal.add(btnBarraSair);

        lblRodape.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblRodape.setForeground(new java.awt.Color(0, 0, 255));
        lblRodape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRodape.setText("Escolha uma das opções do menu");
        lblRodape.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblRodape.setFocusable(false);
        lblRodape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        dskPrincipal.setBackground(new java.awt.Color(192, 192, 192));

        barraMenuPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        menuSuperiorCaixa.setMnemonic('X');
        menuSuperiorCaixa.setText("Caixa");

        menuCadastroCodigos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroCodigos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar_codigos_22x22.png"))); // NOI18N
        menuCadastroCodigos.setMnemonic('C');
        menuCadastroCodigos.setText("Entrada de Códigos");
        menuCadastroCodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCodigos(evt);
            }
        });
        menuSuperiorCaixa.add(menuCadastroCodigos);
        menuSuperiorCaixa.add(sep1);

        menuAbrirCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuAbrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/abrir_caixa_22x22.png"))); // NOI18N
        menuAbrirCaixa.setMnemonic('A');
        menuAbrirCaixa.setText("Abrir Caixa");
        menuAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCaixa(evt);
            }
        });
        menuSuperiorCaixa.add(menuAbrirCaixa);

        menuFecharCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar_caixa_22x22.png"))); // NOI18N
        menuFecharCaixa.setMnemonic('F');
        menuFecharCaixa.setText("Fechar Caixa");
        menuFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharCaixa(evt);
            }
        });
        menuSuperiorCaixa.add(menuFecharCaixa);
        menuSuperiorCaixa.add(sep2);

        menuMovimentarCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuMovimentarCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/movimentar_caixa_22x22.png"))); // NOI18N
        menuMovimentarCaixa.setMnemonic('M');
        menuMovimentarCaixa.setText("Movimentar Caixa");
        menuMovimentarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movimentarCaixa(evt);
            }
        });
        menuSuperiorCaixa.add(menuMovimentarCaixa);

        barraMenuPrincipal.add(menuSuperiorCaixa);

        menuConsulta.setMnemonic('C');
        menuConsulta.setText("Consulta");

        menuTotalVendidoCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuTotalVendidoCaixa.setMnemonic('t');
        menuTotalVendidoCaixa.setText("Total Vendido Por Caixa");
        menuTotalVendidoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalVendidoCaixa(evt);
            }
        });
        menuConsulta.add(menuTotalVendidoCaixa);

        barraMenuPrincipal.add(menuConsulta);

        menuSuperiorSair.setMnemonic('S');
        menuSuperiorSair.setText("Sair");

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair_22x22.png"))); // NOI18N
        menuSair.setMnemonic('S');
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair(evt);
            }
        });
        menuSuperiorSair.add(menuSair);

        barraMenuPrincipal.add(menuSuperiorSair);

        setJMenuBar(barraMenuPrincipal);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(barraFerramentasPrincipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
            .add(lblRodape, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
            .add(dskPrincipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(barraFerramentasPrincipal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dskPrincipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblRodape))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalVendidoCaixa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalVendidoCaixa
        if (totalVendidoCaixa == null) {
            totalVendidoCaixa = new TotalVendidoCaixa();
        }
        SwingHelper.centralizarFrame(totalVendidoCaixa);
        totalVendidoCaixa.setVisible(true);
    }//GEN-LAST:event_totalVendidoCaixa

    private void fecharCaixa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharCaixa
        if (fecharCaixa == null) {
            fecharCaixa = new FecharCaixa();
        }
        SwingHelper.centralizarFrame(fecharCaixa);
        fecharCaixa.setVisible(true);
        fecharCaixa.iniciarFechamentoCaixa();
    }//GEN-LAST:event_fecharCaixa

    private void sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair
        dispose();
    }//GEN-LAST:event_sair

    private void cadastroCodigos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCodigos
        if (cadastroCodigoBarras == null) {
            cadastroCodigoBarras = new CadastroCodigoBarras();
        }
        SwingHelper.centralizarFrame(cadastroCodigoBarras);
        cadastroCodigoBarras.setVisible(true);
    }//GEN-LAST:event_cadastroCodigos

    private void abrirCaixa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCaixa
        if (abrirCaixa == null) {
            abrirCaixa = new AbrirCaixa();
        }
        SwingHelper.centralizarFrame(abrirCaixa);
        abrirCaixa.setVisible(true);
        abrirCaixa.iniciarAberturaCaixa();
    }//GEN-LAST:event_abrirCaixa

    private void movimentarCaixa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movimentarCaixa
        if (movimentoCaixa == null) {
            movimentoCaixa = new MovimentoCaixa();
        }
        SwingHelper.centralizarFrame(movimentoCaixa);
        movimentoCaixa.setVisible(true);
        movimentoCaixa.requestFocus();
        movimentoCaixa.iniciarFrame();
    }//GEN-LAST:event_movimentarCaixa

    private void getKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getKey
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ESCAPE) {
            // Teclar [Esc]
            sair(null);
        }
    }//GEN-LAST:event_getKey

    public void keyTyped(KeyEvent event) {
        getKey(event);
    }

    public void keyPressed(KeyEvent event) {
        getKey(event);
    }

    public void keyReleased(KeyEvent event) {
        getKey(event);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraFerramentasPrincipal;
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JButton btnBarraAbrirCaixa;
    private javax.swing.JButton btnBarraCadastroCodigosProdutos;
    private javax.swing.JButton btnBarraFecharCaixa;
    private javax.swing.JButton btnBarraMovimentarCaixa;
    private javax.swing.JButton btnBarraSair;
    private javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JLabel lblRodape;
    private javax.swing.JMenuItem menuAbrirCaixa;
    private javax.swing.JMenuItem menuCadastroCodigos;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuFecharCaixa;
    private javax.swing.JMenuItem menuMovimentarCaixa;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuSuperiorCaixa;
    private javax.swing.JMenu menuSuperiorSair;
    private javax.swing.JMenuItem menuTotalVendidoCaixa;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    // End of variables declaration//GEN-END:variables
}
