/*
 * FecharCaixa.java
 *
 * Created on 11 de Julho de 2007, 18:29
 */

package com.github.andrepenteado.contest.desktop;

import java.awt.event.KeyEvent;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

import com.github.andrepenteado.contest.entity.Caixa;
import com.github.andrepenteado.contest.services.VendaService;
import com.github.andrepenteado.core.ServicesFactory;
import com.github.andrepenteado.exception.ServiceValidationException;
import com.github.andrepenteado.util.ConfigHelper;
import com.github.andrepenteado.util.FunctionsHelper;
import com.github.andrepenteado.util.Log4jWrapper;
import com.github.andrepenteado.util.SwingHelper;

/**
 *
 * @author  andre
 */
public class FecharCaixa extends javax.swing.JFrame {

    private static final long serialVersionUID = 1659692586420147755L;
    private Log4jWrapper log = new Log4jWrapper(AbrirCaixa.class, Login.getUserLogin());
    private VendaService vendaService = null;
    private Caixa caixa = null;

    /** Creates new form FecharCaixa */
    public FecharCaixa() {
        try {
            if (Login.getUserLogin() == null) {
                throw new Exception(ConfigHelper.get().getString("error.accessDenied"));
            }
            vendaService = (VendaService)ServicesFactory.getInstance(VendaService.class, new Object[] { Login.getUserLogin() });
            initComponents();
        }
        catch (Exception ex) {
            log.fatal("AÇÕES NÃO INSTANCIADAS: ".concat(FecharCaixa.class.getName()), ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), ConfigHelper.get().getString("error.general"), JOptionPane.ERROR_MESSAGE);
        }
    }

    public void iniciarFechamentoCaixa() {
        try {
            caixa = vendaService.buscarCaixaAbertoPorFuncionario(Login.getUserLogin().getFuncionario());
            if (caixa == null) {
                log.debug(ConfigHelper.getProperty("error.notFound", "Caixa Aberto"));
                JOptionPane.showMessageDialog(this, ConfigHelper.getProperty("error.notFound", "Caixa Aberto"), "Atenção",
                                JOptionPane.WARNING_MESSAGE);
                btnCancelarActionPerformed(null);
                return;
            }
            double totalVenda = vendaService.calcularTotalVendidoCaixa(caixa.getId().intValue()).doubleValue();
            double totalDespesa = 0;
            txtNome.setText(caixa.getFuncionario().getNome());
            txtDataAbertura.setText(FunctionsHelper.dateFormat(caixa.getDataAbertura(), "dd/MM/yyyy").concat(" - ").concat(caixa.getHoraAbertura()));
            txtTotalVendas.setText(FunctionsHelper.numberFormat(totalVenda, "###,##0.00"));
            txtTotalDespesas.setText(FunctionsHelper.numberFormat(totalDespesa, "###,##0.00"));
            txtInicialCaixa.setText(FunctionsHelper.numberFormat(caixa.getValorAbertura().doubleValue(), "###,##0.00"));
            txtSaldo.setText(FunctionsHelper.numberFormat(totalVenda + caixa.getValorAbertura().doubleValue() - totalDespesa, "###,##0.00"));
            txtValorGaveta.requestFocus();
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblDataAbertura = new javax.swing.JLabel();
        txtDataAbertura = new javax.swing.JTextField();
        sepMeio2 = new javax.swing.JSeparator();
        lblTotalVendas = new javax.swing.JLabel();
        txtTotalVendas = new javax.swing.JTextField();
        lblTotalDespesas = new javax.swing.JLabel();
        txtTotalDespesas = new javax.swing.JTextField();
        lblInicialCaixa = new javax.swing.JLabel();
        txtInicialCaixa = new javax.swing.JTextField();
        lblSaldo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        sepMeio = new javax.swing.JSeparator();
        lblValorGaveta = new javax.swing.JLabel();
        txtValorGaveta = new javax.swing.JTextField();
        lblDiferenca = new javax.swing.JLabel();
        txtDiferenca = new javax.swing.JTextField();
        btnFecharCaixa = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblCabecalho = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(ConfigHelper.get().getString("sistema.nome") + " :: Fechamento de Caixa");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/logotipo.png")));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("Nome");

        txtNome.setEditable(false);
        txtNome.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtNome.setForeground(java.awt.Color.blue);
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblDataAbertura.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblDataAbertura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataAbertura.setText("Data de Abertura");

        txtDataAbertura.setEditable(false);
        txtDataAbertura.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtDataAbertura.setForeground(java.awt.Color.blue);
        txtDataAbertura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblTotalVendas.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblTotalVendas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalVendas.setText("Total de Vendas");

        txtTotalVendas.setEditable(false);
        txtTotalVendas.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtTotalVendas.setForeground(java.awt.Color.blue);
        txtTotalVendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblTotalDespesas.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblTotalDespesas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalDespesas.setText("Total de Despesas");

        txtTotalDespesas.setEditable(false);
        txtTotalDespesas.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtTotalDespesas.setForeground(java.awt.Color.blue);
        txtTotalDespesas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblInicialCaixa.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblInicialCaixa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInicialCaixa.setText("Inicial do Caixa");

        txtInicialCaixa.setEditable(false);
        txtInicialCaixa.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtInicialCaixa.setForeground(java.awt.Color.blue);
        txtInicialCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblSaldo.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldo.setText("Saldo");

        txtSaldo.setEditable(false);
        txtSaldo.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtSaldo.setForeground(java.awt.Color.blue);
        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblValorGaveta.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblValorGaveta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorGaveta.setText("Valor da Gaveta");

        txtValorGaveta.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtValorGaveta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                exibirDiferenca(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarMoeda(evt);
            }
        });

        lblDiferenca.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblDiferenca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiferenca.setText("Diferença");

        txtDiferenca.setEditable(false);
        txtDiferenca.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtDiferenca.setForeground(java.awt.Color.blue);
        txtDiferenca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        btnFecharCaixa.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnFecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar_22x22.png"))); // NOI18N
        btnFecharCaixa.setText("Fechar Caixa");
        btnFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharCaixaActionPerformed(evt);
            }
        });
        btnFecharCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_22x22.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setDefaultCapable(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCabecalho.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        lblCabecalho.setForeground(java.awt.Color.blue);
        lblCabecalho.setText("Fechamento de Caixa");
        lblCabecalho.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.png"))); // NOI18N

        lblMensagem.setFont(new java.awt.Font("DejaVu Sans", 1, 10));
        lblMensagem.setForeground(java.awt.Color.red);
        lblMensagem.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(lblCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogotipo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogotipo, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataAbertura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalVendas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalDespesas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInicialCaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorGaveta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiferenca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtDataAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtTotalVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtTotalDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtInicialCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtValorGaveta, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtDiferenca, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                    .addComponent(sepMeio, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(sepMeio2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(btnFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtDataAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepMeio2, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtTotalVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtTotalDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblInicialCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addComponent(txtInicialCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepMeio, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorGaveta, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtValorGaveta, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiferenca, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtDiferenca, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharCaixa)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exibirDiferenca(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exibirDiferenca
        try {
            double valorGaveta = Float.parseFloat(((JTextField)evt.getSource()).getText().replace(',', '.'));
            double valorSaldo = Float.parseFloat(txtSaldo.getText().replace(',', '.'));
            double diferenca = valorGaveta - valorSaldo;
            txtDiferenca.setText(FunctionsHelper.numberFormat(diferenca, "###,##0.00"));
        }
        catch (Exception ex) {
            txtDiferenca.setText("E");
        }
    }//GEN-LAST:event_exibirDiferenca

    private void validarMoeda(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarMoeda
        SwingHelper.validarMoeda(evt);
    }//GEN-LAST:event_validarMoeda

    private void btnFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharCaixaActionPerformed
        try {
            if (txtValorGaveta.getText().equals("")) {
                log.debug(ConfigHelper.getProperty("error.required", "Valor da Gaveta"));
                throw new ServiceValidationException(ConfigHelper.getProperty("error.required", "Valor da Gaveta"));
            }
            caixa.setValorFechamento(new Double(txtValorGaveta.getText().replace(',', '.')));
            caixa.setDataFechamento(new Date());
            caixa.setHoraFechamento(FunctionsHelper.dateFormat(new Date(), "HH:mm"));
            caixa.gravar();
            String relatorio = vendaService.gerarListagemFechamentoCaixa(caixa.getId().intValue());
            Relatorio fechamento = new Relatorio(this, relatorio);
            SwingHelper.centralizarFrame(fechamento);
            fechamento.setVisible(true);
            btnCancelarActionPerformed(null);
        }
        catch (ServiceValidationException sve) {
            SwingHelper.exibeMensagemTemporaria(lblMensagem, sve.getMessage());
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }
    }//GEN-LAST:event_btnFecharCaixaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void getKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getKey
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ESCAPE) {
            btnCancelarActionPerformed(null);
        }
        else if (tecla == KeyEvent.VK_ENTER) {
            btnFecharCaixaActionPerformed(null);
        }
    }//GEN-LAST:event_getKey

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFecharCaixa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblDataAbertura;
    private javax.swing.JLabel lblDiferenca;
    private javax.swing.JLabel lblInicialCaixa;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTotalDespesas;
    private javax.swing.JLabel lblTotalVendas;
    private javax.swing.JLabel lblValorGaveta;
    private javax.swing.JSeparator sepMeio;
    private javax.swing.JSeparator sepMeio2;
    private javax.swing.JTextField txtDataAbertura;
    private javax.swing.JTextField txtDiferenca;
    private javax.swing.JTextField txtInicialCaixa;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTotalDespesas;
    private javax.swing.JTextField txtTotalVendas;
    private javax.swing.JTextField txtValorGaveta;
    // End of variables declaration//GEN-END:variables
}
