/*
 * FinalizarVenda.java
 *
 * Created on 31 de Março de 2007, 12:40
 */

package com.github.andrepenteado.contest.desktop;

import java.awt.Event;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

import com.github.andrepenteado.contest.entity.Venda;
import com.github.andrepenteado.contest.entity.valueObject.FormaPagamento;
import com.github.andrepenteado.contest.services.VendaService;
import com.github.andrepenteado.core.ServicesFactory;
import com.github.andrepenteado.exception.ServiceValidationException;
import com.github.andrepenteado.util.ConfigHelper;
import com.github.andrepenteado.util.FunctionsHelper;
import com.github.andrepenteado.util.Log4jWrapper;
import com.github.andrepenteado.util.SwingHelper;

/**
 *
 * @author  Andre Penteado
 */
public class FinalizarVenda extends javax.swing.JDialog {

    private static final long serialVersionUID = -1596317797730484435L;
    private Log4jWrapper log = new Log4jWrapper(FinalizarVenda.class, Login.getUserLogin());
    private Venda venda = null;
    private VendaService vendaService = null;

    /** Creates new form FinalizarVenda */
    public FinalizarVenda(java.awt.Frame parent, boolean modal, Venda venda) {
        super(parent, modal);
        try {
            if (Login.getUserLogin() == null) {
                throw new Exception(ConfigHelper.get().getString("error.accessDenied"));
            }
            vendaService = (VendaService)ServicesFactory.getInstance(VendaService.class, new Object[] { Login.getUserLogin() });
            this.venda = venda;
            initComponents();
            iniciarFrame();
        }
        catch (Exception ex) {
            log.fatal("AÇÕES NÃO INSTANCIADAS: ".concat(MovimentoCaixa.class.getName()), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }
    }

    private void iniciarFrame() {
        String total = FunctionsHelper.numberFormat(venda.getValorTotalProduto(), "###,##0.00");
        lblTotalPagar.setText("R$ ".concat(total));
        lblTroco.setText("0,00");
        txtValorPago.setText(total);
        txtValorPago.requestFocus();
        txtValorPago.selectAll();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopo = new javax.swing.JLabel();
        lblTotalPagar = new javax.swing.JLabel();
        lblFormaPagamento = new javax.swing.JLabel();
        cboPrazoPagamento = new javax.swing.JComboBox();
        lblValorPago = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        lblLabelTroco = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnConcluir = new javax.swing.JButton();
        pnlTopo = new javax.swing.JPanel();
        lblCabecalho = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ConfigHelper.get().getString("sistema.nome") + " :: Finalizar Venda");
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblTopo.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblTopo.setForeground(new java.awt.Color(255, 0, 0));
        lblTopo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTopo.setText("T O T A L:  R$");

        lblTotalPagar.setFont(new java.awt.Font("Tahoma", 1, 24));
        lblTotalPagar.setForeground(new java.awt.Color(0, 0, 255));
        lblTotalPagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblFormaPagamento.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblFormaPagamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFormaPagamento.setText("Forma de Pagamento [F12]");

        cboPrazoPagamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboPrazoPagamento.setModel(new javax.swing.DefaultComboBoxModel(FormaPagamento.values()));
        cboPrazoPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblValorPago.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblValorPago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorPago.setText("Valor Pago (R$) [F11]");

        txtValorPago.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                exibirTroco(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarMoeda(evt);
            }
        });

        lblLabelTroco.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblLabelTroco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLabelTroco.setText("Troco (R$)");

        lblTroco.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblTroco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_22x22.png"))); // NOI18N
        btnVoltar.setText("Voltar [Esc]");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        btnConcluir.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnConcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar_22x22.png"))); // NOI18N
        btnConcluir.setText("Concluir [Ctrl+F10]");
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });
        btnConcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        pnlTopo.setBackground(java.awt.Color.white);
        pnlTopo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCabecalho.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        lblCabecalho.setForeground(java.awt.Color.blue);
        lblCabecalho.setText("Finalizar Venda");
        lblCabecalho.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.png"))); // NOI18N

        lblMensagem.setFont(new java.awt.Font("DejaVu Sans", 1, 10));
        lblMensagem.setForeground(java.awt.Color.red);
        lblMensagem.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout pnlTopoLayout = new org.jdesktop.layout.GroupLayout(pnlTopo);
        pnlTopo.setLayout(pnlTopoLayout);
        pnlTopoLayout.setHorizontalGroup(pnlTopoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        org.jdesktop.layout.GroupLayout.TRAILING,
                        pnlTopoLayout.createSequentialGroup().addContainerGap().add(
                                        pnlTopoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblMensagem,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE).add(lblCabecalho,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)).addPreferredGap(
                                        org.jdesktop.layout.LayoutStyle.RELATED).add(lblLogotipo).addContainerGap()));
        pnlTopoLayout.setVerticalGroup(pnlTopoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblLogotipo,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE).add(
                        pnlTopoLayout.createSequentialGroup().add(lblCabecalho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                                        lblMensagem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        layout.createSequentialGroup().addContainerGap().add(
                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false).add(
                                                        org.jdesktop.layout.GroupLayout.LEADING, lblTopo,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE).add(lblLabelTroco, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).add(
                                                        org.jdesktop.layout.GroupLayout.LEADING, lblValorPago,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE).add(org.jdesktop.layout.GroupLayout.LEADING, lblFormaPagamento,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)).add(18, 18, 18).add(
                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                                                        org.jdesktop.layout.GroupLayout.TRAILING, lblTotalPagar,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE).add(txtValorPago,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE).add(cboPrazoPagamento, 0,
                                                        255, Short.MAX_VALUE).add(lblTroco, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 255,
                                                        Short.MAX_VALUE)).addContainerGap()).add(pnlTopo,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).add(
                        org.jdesktop.layout.GroupLayout.TRAILING,
                        layout.createSequentialGroup().addContainerGap(103, Short.MAX_VALUE).add(btnConcluir).addPreferredGap(
                                        org.jdesktop.layout.LayoutStyle.RELATED).add(btnVoltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap()));

        layout.linkSize(new java.awt.Component[] { btnConcluir, btnVoltar }, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        layout.createSequentialGroup().add(pnlTopo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(8, 8, 8)
                                        .add(
                                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblTotalPagar,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(lblTopo))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(lblFormaPagamento,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(cboPrazoPagamento,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.RELATED).add(
                                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(lblValorPago,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(txtValorPago,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.RELATED).add(
                                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblLabelTroco,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(lblTroco,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24,
                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
                                                        org.jdesktop.layout.LayoutStyle.RELATED).add(
                                                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(btnVoltar).add(
                                                                        btnConcluir)).addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)));

        layout.linkSize(new java.awt.Component[] { cboPrazoPagamento, lblTroco, txtValorPago }, org.jdesktop.layout.GroupLayout.VERTICAL);

        layout.linkSize(new java.awt.Component[] { btnConcluir, btnVoltar }, org.jdesktop.layout.GroupLayout.VERTICAL);

        layout.linkSize(new java.awt.Component[] { lblTopo, lblTotalPagar }, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exibirTroco(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exibirTroco
        if (txtValorPago != null && !txtValorPago.getText().equals("")) {
            double pago = Double.parseDouble(txtValorPago.getText().replace(',', '.'));
            double total = Double.parseDouble(lblTotalPagar.getText().replace(',', '.').replace("R$ ", ""));
            lblTroco.setText(FunctionsHelper.numberFormat(pago - total, "###,##0.00"));
        }
        else
            lblTroco.setText("0,00");
    }//GEN-LAST:event_exibirTroco

    private void validarMoeda(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarMoeda
        SwingHelper.validarMoeda(evt);
    }//GEN-LAST:event_validarMoeda

    private void getKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getKey
        int tecla = evt.getKeyCode();
        int modificador = evt.getModifiers();
        if (tecla == KeyEvent.VK_ESCAPE) // [Esc] Voltar para a tela de vendas
            btnVoltarActionPerformed(null);
        if (tecla == KeyEvent.VK_F12) { // [F12] Escolher Forma de Pagamento
            cboPrazoPagamento.requestFocus();
            cboPrazoPagamento.setSelectedIndex(0);
        }
        else if (tecla == KeyEvent.VK_F11) { // [F11] Digitar Valor Pago
            txtValorPago.requestFocus();
            txtValorPago.selectAll();
        }
        else if (tecla == KeyEvent.VK_F10 && modificador == Event.CTRL_MASK) { // [Ctrl+F10] Concluir Venda
            btnConcluirActionPerformed(null);
        }
    }//GEN-LAST:event_getKey

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(this, ConfigHelper.getProperty("warning.save", "Venda"), "Pergunta", JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE) == 0) {

                String relatorio = vendaService.gravarNovaVendaCaixa(venda, vendaService.buscarCaixaAbertoPorFuncionario(Login.getUserLogin()
                                .getFuncionario()), (FormaPagamento)cboPrazoPagamento.getSelectedItem());
                Relatorio fechamento = new Relatorio(this, relatorio);
                SwingHelper.centralizarFrame(fechamento);
                fechamento.setVisible(true);
                dispose();
            }
        }
        catch (ServiceValidationException saie) {
            SwingHelper.exibeMensagemTemporaria(lblMensagem, saie.getMessage());
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }
    }//GEN-LAST:event_btnConcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox cboPrazoPagamento;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblLabelTroco;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTopo;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblValorPago;
    private javax.swing.JPanel pnlTopo;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables

}