/*
 * Login.java
 *
 * Created on 13 de Julho de 2007, 19:07
 */

package com.github.andrepenteado.contest.desktop;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Iterator;

import com.github.andrepenteado.contest.KGlobal;
import com.github.andrepenteado.contest.entity.Categoria;
import com.github.andrepenteado.contest.entity.Funcionario;
import com.github.andrepenteado.contest.services.LoginService;
import com.github.andrepenteado.core.ApplicationService;
import com.github.andrepenteado.core.ServicesFactory;
import com.github.andrepenteado.exception.ServiceValidationException;
import com.github.andrepenteado.util.ConfigHelper;
import com.github.andrepenteado.util.FunctionsHelper;
import com.github.andrepenteado.util.Log4jWrapper;
import com.github.andrepenteado.util.SettingsConfig;
import com.github.andrepenteado.util.SwingHelper;
import com.github.andrepenteado.util.UsuarioLogadoWrapper;
import com.github.andrepenteado.web.ServletInitListener;

/**
 *
 * @author  andre
 */
public class Login extends javax.swing.JFrame {

    private static final long serialVersionUID = -6005208402415282744L;
    private static UsuarioLogadoWrapper userLogin = null;
    private Log4jWrapper log;

    /** Creates new form Login */
    public Login() {
        System.setProperty(SettingsConfig.K_PROPRIEDADE_ROOT_CLASSPATH, FunctionsHelper.getRootClassPath(Desktop.class));
        ConfigHelper.load();
        Log4jWrapper.initConfig();
        new ApplicationService();
        log = new Log4jWrapper(ServletInitListener.class, null);
        System.setProperty(SettingsConfig.K_PROPRIEDADE_ROOT_CLASSPATH, "");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        pnlTopo = new javax.swing.JPanel();
        lblCabecalho = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(ConfigHelper.get().getString("sistema.nome") + " :: Login");
        setAlwaysOnTop(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/logotipo.png")));
        setResizable(false);

        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar_22x22.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setDefaultCapable(false);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        btnEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        pnlTopo.setBackground(java.awt.Color.white);
        pnlTopo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCabecalho.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblCabecalho.setForeground(java.awt.Color.blue);
        lblCabecalho.setText("Módulo PDV");
        lblCabecalho.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.png"))); // NOI18N

        lblMensagem.setFont(new java.awt.Font("DejaVu Sans", 1, 10));
        lblMensagem.setForeground(java.awt.Color.red);
        lblMensagem.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlTopoLayout = new javax.swing.GroupLayout(pnlTopo);
        pnlTopo.setLayout(pnlTopoLayout);
        pnlTopoLayout.setHorizontalGroup(pnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        pnlTopoLayout.createSequentialGroup().addContainerGap().addGroup(
                                        pnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblMensagem,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE).addComponent(lblCabecalho,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblLogotipo).addContainerGap()));
        pnlTopoLayout.setVerticalGroup(pnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblLogotipo,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE).addGroup(
                        pnlTopoLayout.createSequentialGroup().addComponent(lblCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("E-mail");

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailGetKey(evt);
            }
        });

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSenha.setText("Senha");

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaGetKey(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(pnlTopo,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(
                        layout.createSequentialGroup().addContainerGap().addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblEmail).addComponent(
                                                        lblSenha)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(txtEmail,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE).addComponent(txtSenha,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)).addGap(13, 13, 13)).addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup().addGap(232, 232, 232).addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 142,
                                        Short.MAX_VALUE).addContainerGap()));
        layout
                        .setVerticalGroup(layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(
                                                        layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(pnlTopo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(
                                                                                        layout
                                                                                                        .createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addGroup(
                                                                                                                        layout
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .addComponent(
                                                                                                                                                        txtEmail,
                                                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                        26,
                                                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                        .addPreferredGap(
                                                                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                        6,
                                                                                                                                                        Short.MAX_VALUE))
                                                                                                        .addComponent(
                                                                                                                        lblEmail,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        32, Short.MAX_VALUE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(
                                                                                        layout
                                                                                                        .createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                        .addComponent(
                                                                                                                        lblSenha,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        37, Short.MAX_VALUE)
                                                                                                        .addComponent(
                                                                                                                        txtSenha,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18).addComponent(btnEntrar).addGap(11, 11, 11)));

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { txtEmail, txtSenha });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static UsuarioLogadoWrapper getUserLogin() {
        return userLogin;
    }

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        try {
            LoginService loginService = (LoginService)ServicesFactory.getInstance(LoginService.class, null);
            Funcionario funcionario = loginService.authenticator(txtEmail.getText(), new String(txtSenha.getPassword()), FunctionsHelper
                            .getLocalHostName());
            if (funcionario != null && !funcionario.getCategorias().isEmpty()) {
                userLogin = new UsuarioLogadoWrapper();
                userLogin.setFuncionario(funcionario);
                Iterator<Categoria> it = funcionario.getCategorias().iterator();
                while (it.hasNext()) {
                    Categoria categoria = it.next();
                    if (KGlobal.CATEGORIA_PDV.equals(categoria.getNome())) {
                        userLogin.setCategoriaAtual(categoria);
                    }
                }
                if (userLogin.getCategoriaAtual() == null || userLogin.getFuncionario().getEmpresa() == null) {
                    throw new ServiceValidationException(ConfigHelper.get().getString("error.accessDenied"));
                }
            }
            Desktop desktop = new Desktop();
            SwingHelper.centralizarFrame(desktop);
            desktop.setVisible(true);
            dispose();
        }
        catch (ServiceValidationException unex) {
            log.debug(unex.getMessage());
            SwingHelper.exibeMensagemTemporaria(lblMensagem, unex.getMessage());
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void getKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getKey
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ESCAPE) {
            dispose();
        }
        else if (tecla == KeyEvent.VK_ENTER) {
            btnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_getKey

    private void txtEmailGetKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailGetKey
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ESCAPE) {
            dispose();
        }
        else if (tecla == KeyEvent.VK_ENTER) {
            btnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_txtEmailGetKey

    private void txtSenhaGetKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaGetKey
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ESCAPE) {
            dispose();
        }
        else if (tecla == KeyEvent.VK_ENTER) {
            btnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_txtSenhaGetKey

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Login login = new Login();
                SwingHelper.centralizarFrame(login);
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel pnlTopo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}