/*
 * MovimentoCaixa.java
 *
 * Created on 29 de Março de 2007, 21:04
 */

package com.github.andrepenteado.contest.desktop;

import java.awt.Event;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import com.github.andrepenteado.contest.entity.Caixa;
import com.github.andrepenteado.contest.entity.Estoque;
import com.github.andrepenteado.contest.entity.ItemVenda;
import com.github.andrepenteado.contest.entity.Produto;
import com.github.andrepenteado.contest.entity.Venda;
import com.github.andrepenteado.contest.filters.ProdutoFilter;
import com.github.andrepenteado.contest.services.CadastroService;
import com.github.andrepenteado.contest.services.VendaService;
import com.github.andrepenteado.core.ServicesFactory;
import com.github.andrepenteado.exception.ServiceValidationException;
import com.github.andrepenteado.util.ConfigHelper;
import com.github.andrepenteado.util.FunctionsHelper;
import com.github.andrepenteado.util.Log4jWrapper;
import com.github.andrepenteado.util.SwingHelper;

/**
 *
 * @author  Andre Penteado
 */
public class MovimentoCaixa extends javax.swing.JFrame {

    private static final long serialVersionUID = 9217352616698895108L;
    private Log4jWrapper log = new Log4jWrapper(MovimentoCaixa.class, Login.getUserLogin());
    private VendaService vendaService = null;
    private CadastroService cadastroService = null;
    private Double totalVenda;
    private List<ItemVenda> itens;
    private Venda venda;
    private Produto produtoAtual;

    /** Creates new form MovimentoCaixa */
    public MovimentoCaixa() {
        try {
            if (Login.getUserLogin() == null) {
                throw new Exception(ConfigHelper.get().getString("error.accessDenied"));
            }
            vendaService = (VendaService)ServicesFactory.getInstance(VendaService.class, new Object[] { Login.getUserLogin() });
            cadastroService = (CadastroService)ServicesFactory.getInstance(CadastroService.class, new Object[] { Login.getUserLogin() });
            initComponents();
        }
        catch (Exception ex) {
            log.fatal("AÇÕES NÃO INSTANCIADAS: ".concat(MovimentoCaixa.class.getName()), ex);
            JOptionPane.showMessageDialog(this, ConfigHelper.get().getString("error.general"), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOperador = new javax.swing.JLabel();
        lblNumeroCaixa = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblNomeProduto = new javax.swing.JLabel();
        scrListaItens = new javax.swing.JScrollPane();
        lstItens = new javax.swing.JList();
        lblSubTotal = new javax.swing.JLabel();
        btnFinalizarVenda = new javax.swing.JButton();
        btnExtornarProduto = new javax.swing.JButton();
        btnCancelarVenda = new javax.swing.JButton();
        pnlTopo = new javax.swing.JPanel();
        lblCabecalho = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ConfigHelper.get().getString("sistema.nome") + " :: Caixa");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/logotipo.png")));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblOperador.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblOperador.setForeground(new java.awt.Color(255, 0, 0));
        lblOperador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOperador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblNumeroCaixa.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblNumeroCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroCaixa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblData.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblProduto.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblProduto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProduto.setText("Produto [F2]");

        txtCodigoProduto.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtCodigoProduto.setForeground(new java.awt.Color(0, 153, 0));
        txtCodigoProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoActionPerformed(evt);
            }
        });
        txtCodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblPreco.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblPreco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPreco.setText("Preço [F3]");

        txtPreco.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtPreco.setForeground(new java.awt.Color(0, 153, 0));
        txtPreco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPreco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        txtPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarMoeda(evt);
            }
        });

        lblQuantidade.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblQuantidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQuantidade.setText("QTD [F4]");

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtQuantidade.setForeground(new java.awt.Color(0, 153, 0));
        txtQuantidade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQuantidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                validarNumeroInteiro(evt);
            }
        });

        lblNomeProduto.setFont(new java.awt.Font("Tahoma", 1, 24));
        lblNomeProduto.setForeground(new java.awt.Color(0, 0, 255));
        lblNomeProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lstItens.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lstItens.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        DefaultListModel dlm = new DefaultListModel();
        lstItens.setModel(dlm);
        lstItens.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstItens.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lstItensFocusLost(evt);
            }
        });
        lstItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });
        scrListaItens.setViewportView(lstItens);

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 36));
        lblSubTotal.setForeground(new java.awt.Color(0, 0, 255));
        lblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnFinalizarVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFinalizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar_22x22.png"))); // NOI18N
        btnFinalizarVenda.setText("Finalizar Venda [Ctrl+F5]");
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });
        btnFinalizarVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        btnExtornarProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExtornarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir_22x22.png"))); // NOI18N
        btnExtornarProduto.setText("Extornar Produto [Ctrl+Del]");
        btnExtornarProduto.setActionCommand("Extornar Produto [DEL]");
        btnExtornarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtornarProdutoActionPerformed(evt);
            }
        });
        btnExtornarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        btnCancelarVenda.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnCancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_22x22.png"))); // NOI18N
        btnCancelarVenda.setText("Cancelar Venda [Esc]");
        btnCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVendaActionPerformed(evt);
            }
        });
        btnCancelarVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        pnlTopo.setBackground(java.awt.Color.white);
        pnlTopo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCabecalho.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblCabecalho.setForeground(java.awt.Color.blue);
        lblCabecalho.setText(Login.getUserLogin().getFuncionario().getEmpresa().getNomeFantasia() + " - Venda no Caixa");
        lblCabecalho.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.png"))); // NOI18N

        lblMensagem.setFont(new java.awt.Font("DejaVu Sans", 1, 10));
        lblMensagem.setForeground(java.awt.Color.red);
        lblMensagem.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout pnlTopoLayout = new org.jdesktop.layout.GroupLayout(pnlTopo);
        pnlTopo.setLayout(pnlTopoLayout);
        pnlTopoLayout.setHorizontalGroup(pnlTopoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        org.jdesktop.layout.GroupLayout.TRAILING,
                        pnlTopoLayout.createSequentialGroup().addContainerGap().add(
                                        pnlTopoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblMensagem,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE).add(lblCabecalho,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)).addPreferredGap(
                                        org.jdesktop.layout.LayoutStyle.RELATED).add(lblLogotipo).addContainerGap()));
        pnlTopoLayout.setVerticalGroup(pnlTopoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(lblLogotipo,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE).add(
                        pnlTopoLayout.createSequentialGroup().add(lblCabecalho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(
                                        lblMensagem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout
                        .setHorizontalGroup(layout
                                        .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(
                                                        layout
                                                                        .createSequentialGroup()
                                                                        .addContainerGap()
                                                                        .add(
                                                                                        layout
                                                                                                        .createParallelGroup(
                                                                                                                        org.jdesktop.layout.GroupLayout.LEADING)
                                                                                                        .add(
                                                                                                                        scrListaItens,
                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                        764, Short.MAX_VALUE)
                                                                                                        .add(
                                                                                                                        org.jdesktop.layout.GroupLayout.TRAILING,
                                                                                                                        layout
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .add(
                                                                                                                                                        btnCancelarVenda,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                        240,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                                                        .addPreferredGap(
                                                                                                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                                                                                        .add(
                                                                                                                                                        btnExtornarProduto,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                        272,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                                                        .addPreferredGap(
                                                                                                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                                                                                        .add(
                                                                                                                                                        btnFinalizarVenda,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                        240,
                                                                                                                                                        Short.MAX_VALUE))
                                                                                                        .add(
                                                                                                                        org.jdesktop.layout.GroupLayout.TRAILING,
                                                                                                                        lblSubTotal,
                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                        764, Short.MAX_VALUE)
                                                                                                        .add(
                                                                                                                        org.jdesktop.layout.GroupLayout.TRAILING,
                                                                                                                        layout
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .add(
                                                                                                                                                        lblOperador,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                        499,
                                                                                                                                                        Short.MAX_VALUE)
                                                                                                                                        .addPreferredGap(
                                                                                                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                                                                                        .add(
                                                                                                                                                        layout
                                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.LEADING)
                                                                                                                                                                        .add(
                                                                                                                                                                                        lblData,
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                        217,
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                        .add(
                                                                                                                                                                                        lblNumeroCaixa,
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                        259,
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                                                                                        .add(
                                                                                                                        lblNomeProduto,
                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                        764, Short.MAX_VALUE)
                                                                                                        .add(
                                                                                                                        layout
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .add(
                                                                                                                                                        layout
                                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.LEADING,
                                                                                                                                                                                        false)
                                                                                                                                                                        .add(
                                                                                                                                                                                        lblPreco,
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                        Short.MAX_VALUE)
                                                                                                                                                                        .add(
                                                                                                                                                                                        lblProduto,
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                        96,
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                                                                                                        .addPreferredGap(
                                                                                                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                                                                                        .add(
                                                                                                                                                        layout
                                                                                                                                                                        .createParallelGroup(
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.LEADING)
                                                                                                                                                                        .add(
                                                                                                                                                                                        layout
                                                                                                                                                                                                        .createSequentialGroup()
                                                                                                                                                                                                        .add(
                                                                                                                                                                                                                        txtPreco,
                                                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                        200,
                                                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        .addPreferredGap(
                                                                                                                                                                                                                        org.jdesktop.layout.LayoutStyle.RELATED,
                                                                                                                                                                                                                        244,
                                                                                                                                                                                                                        Short.MAX_VALUE)
                                                                                                                                                                                                        .add(
                                                                                                                                                                                                                        lblQuantidade,
                                                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                        69,
                                                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                                        .addPreferredGap(
                                                                                                                                                                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                                                                                                                                                        .add(
                                                                                                                                                                                                                        txtQuantidade,
                                                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                        147,
                                                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                        .add(
                                                                                                                                                                                        txtCodigoProduto,
                                                                                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                        664,
                                                                                                                                                                                        Short.MAX_VALUE))))
                                                                        .addContainerGap()).add(pnlTopo,
                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE));

        layout.linkSize(new java.awt.Component[] { lblData, lblNumeroCaixa }, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout
                        .setVerticalGroup(layout
                                        .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(
                                                        org.jdesktop.layout.GroupLayout.TRAILING,
                                                        layout
                                                                        .createSequentialGroup()
                                                                        .add(pnlTopo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                        .add(
                                                                                        layout
                                                                                                        .createParallelGroup(
                                                                                                                        org.jdesktop.layout.GroupLayout.LEADING)
                                                                                                        .add(
                                                                                                                        layout
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .add(
                                                                                                                                                        lblNumeroCaixa,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                        28,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                                                        .addPreferredGap(
                                                                                                                                                        org.jdesktop.layout.LayoutStyle.RELATED)
                                                                                                                                        .add(
                                                                                                                                                        lblData,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                        24,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                                                                        .add(
                                                                                                                        lblOperador,
                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                        62,
                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                        .add(
                                                                                        layout
                                                                                                        .createParallelGroup(
                                                                                                                        org.jdesktop.layout.GroupLayout.LEADING)
                                                                                                        .add(lblProduto)
                                                                                                        .add(
                                                                                                                        txtCodigoProduto,
                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                        .add(
                                                                                        layout
                                                                                                        .createParallelGroup(
                                                                                                                        org.jdesktop.layout.GroupLayout.LEADING)
                                                                                                        .add(
                                                                                                                        txtPreco,
                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                        .add(lblPreco)
                                                                                                        .add(
                                                                                                                        txtQuantidade,
                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                        .add(lblQuantidade))
                                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                        .add(lblNomeProduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64,
                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                        .add(scrListaItens, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 170,
                                                                                        Short.MAX_VALUE)
                                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                        .add(lblSubTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50,
                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                        .add(
                                                                                        layout
                                                                                                        .createParallelGroup(
                                                                                                                        org.jdesktop.layout.GroupLayout.LEADING)
                                                                                                        .add(
                                                                                                                        btnFinalizarVenda,
                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                        32,
                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                        .add(
                                                                                                                        layout
                                                                                                                                        .createParallelGroup(
                                                                                                                                                        org.jdesktop.layout.GroupLayout.BASELINE)
                                                                                                                                        .add(
                                                                                                                                                        btnCancelarVenda,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                        34,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                                                        .add(
                                                                                                                                                        btnExtornarProduto,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                        31,
                                                                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                                                        .addContainerGap()));

        layout.linkSize(new java.awt.Component[] { lblData, lblNumeroCaixa, lblPreco, lblProduto, lblQuantidade, txtCodigoProduto, txtPreco,
                        txtQuantidade }, org.jdesktop.layout.GroupLayout.VERTICAL);

        layout.linkSize(new java.awt.Component[] { btnCancelarVenda, btnExtornarProduto, btnFinalizarVenda },
                        org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstItensFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lstItensFocusLost
        lstItens.clearSelection();
    }//GEN-LAST:event_lstItensFocusLost

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        gravarItem();
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        gravarItem();
    }

    public void iniciarFrame() {
        try {
            Caixa caixaAberto = vendaService.buscarCaixaAbertoPorFuncionario(Login.getUserLogin().getFuncionario());
            if (caixaAberto == null) {
                JOptionPane.showMessageDialog(this, ConfigHelper.getProperty("error.notFound", "Caixa aberto"), "Atenção",
                                JOptionPane.WARNING_MESSAGE);
                dispose();
                return;
            }
            lblOperador.setText("OPERADOR: ".concat(caixaAberto.getFuncionario().getNome()));
            lblNumeroCaixa.setText("CAIXA: 00000000".concat(caixaAberto.getId().toString()));
            lblData
                            .setText(FunctionsHelper.dateFormat(caixaAberto.getDataAbertura(), "dd/MM/yyyy").concat(" ").concat(
                                            caixaAberto.getHoraAbertura()));

            if (!FunctionsHelper.dateFormat(caixaAberto.getDataAbertura(), "dd/MM/yyyy").equals(FunctionsHelper.dateFormat(new Date(), "dd/MM/yyyy"))) {
                if (JOptionPane.showConfirmDialog(this, ConfigHelper.get().getString("warning.caixaAbertoDiaDiferente"), "Pergunta",
                                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 1) {
                    dispose();
                }
            }
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
            dispose();
            return;
        }
        iniciarVenda();
    }

    private void iniciarVenda() {
        totalVenda = new Double(0);
        venda = new Venda();
        produtoAtual = new Produto();
        itens = new ArrayList<ItemVenda>();
        DefaultListModel listModel = (DefaultListModel)lstItens.getModel();
        listModel.clear();
        lblSubTotal.setText("R$ 0,00");
        limparCamposItem();
    }

    private void limparCamposItem() {
        txtCodigoProduto.setText("");
        txtPreco.setText("0,00");
        txtQuantidade.setText("1");
        lblNomeProduto.setText("");
        produtoAtual = null;
        txtCodigoProduto.requestFocus();
    }

    private void gravarItem() {
        try {
            if (txtCodigoProduto.getText() == null || txtCodigoProduto.equals("")) {
                throw new ServiceValidationException(ConfigHelper.getProperty("error.required", "Código do Produto"));
            }
            else if (produtoAtual == null) {
                throw new ServiceValidationException(ConfigHelper.getProperty("error.invalid", "Produto"));
            }
            else if (Integer.parseInt(txtQuantidade.getText()) <= 0) {
                throw new ServiceValidationException(ConfigHelper.getProperty("error.greaterThan", new String[] { "Quantidade", "0 (zero)" }));
            }
            else if (Double.parseDouble(txtPreco.getText().replace(',', '.')) == 0f) {
                throw new ServiceValidationException(ConfigHelper.getProperty("error.greaterThan", new String[] { "Preço", "0 (zero)" }));
            }

            ItemVenda item = new ItemVenda();
            for (Estoque estoque : produtoAtual.getEstoques()) {
                if (estoque.getEmpresa().getId().intValue() == Login.getUserLogin().getFuncionario().getEmpresa().getId().intValue())
                    estoque.setSpecIn(estoque.getSpecIn().intValue() - Integer.parseInt(txtQuantidade.getText()));
            }

            item.setProduto(produtoAtual);
            item.setQuantidade(new Integer(txtQuantidade.getText()));
            item.setValorVenda(new Double(txtPreco.getText().replace(',', '.')));
            item.setVenda(venda);

            for (int i = 0; i < itens.size(); i++) {
                ItemVenda aux = (ItemVenda)itens.get(i);
                if (aux.getProduto().getId().intValue() == item.getProduto().getId().intValue()) {
                    throw new ServiceValidationException(ConfigHelper.getProperty("error.found", "Produto"));
                }
            }

            itens.add(item);
            DefaultListModel listModel = (DefaultListModel)lstItens.getModel();
            StringBuilder sb = new StringBuilder();
            sb.append(FunctionsHelper.fillSpacesRight(item.getProduto().getDescricao(), 39));
            sb.append(" ");
            sb.append(FunctionsHelper.fillSpacesLeft(FunctionsHelper.numberFormat(item.getValorVenda().doubleValue(), "###,##0.00"), 7));
            sb.append("  X  ");
            sb.append(FunctionsHelper.fillSpacesLeft(FunctionsHelper.numberFormat(item.getQuantidade(), "####0"), 3));
            sb.append("  =  ");
            sb.append(FunctionsHelper.fillSpacesLeft(FunctionsHelper.numberFormat(item.getValorVenda().doubleValue() * item.getQuantidade(),
                            "###,##0.00"), 7));
            listModel.addElement(sb.toString());

            String subTotal = FunctionsHelper.numberFormat(item.getQuantidade() * item.getValorVenda().doubleValue(), "######0.00");
            totalVenda = new Double(totalVenda.doubleValue() + Double.parseDouble(subTotal.replace(',', '.')));
            lblSubTotal.setText(FunctionsHelper.numberFormat(totalVenda.doubleValue(), "R$ ###,##0.00"));
        }
        catch (ServiceValidationException saie) {
            SwingHelper.exibeMensagemTemporaria(lblMensagem, saie.getMessage());
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }
        limparCamposItem();
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void excluirItem(int index) {
        try {
            if (index == -1) {
                SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.getProperty("error.notSelected", "Item"));
                return;
            }
            if (JOptionPane.showConfirmDialog(this, ConfigHelper.getProperty("warning.delete", "item"), "Pergunta", JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE) == 0) {
                ItemVenda item = (ItemVenda)itens.get(index);
                totalVenda = totalVenda.doubleValue() - (item.getQuantidade() * item.getValorVenda().doubleValue());
                DefaultListModel listModel = (DefaultListModel)lstItens.getModel();
                itens.remove(index);
                listModel.remove(index);
                lblSubTotal.setText(FunctionsHelper.numberFormat(totalVenda.doubleValue(), "R$ ###,##0.00"));
                limparCamposItem();
            }
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }
    }

    private void txtCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoActionPerformed
        try {
            produtoAtual = cadastroService.buscarProdutoPorCodigoBarras(txtCodigoProduto.getText());
            if (produtoAtual == null) {
                produtoAtual = cadastroService.buscarProdutoPorReferencia(txtCodigoProduto.getText());
            }
            if (produtoAtual == null) {
                try {
                    produtoAtual = new Produto(Long.parseLong(txtCodigoProduto.getText()));
                }
                catch (NumberFormatException nfe) {
                }
            }
            if (produtoAtual == null || produtoAtual.getId() == null) {
                ProdutoFilter filter = new ProdutoFilter();
                filter.setDescricao(txtCodigoProduto.getText());
                List<Produto> lstProdutos = new ArrayList<Produto>(filter.executeFilter());

                PopupConsulta popup = new PopupConsulta(this, true, lstProdutos);
                popup.setVisible(true);
                produtoAtual = (Produto)popup.getResult();
                popup.dispose();
                if (produtoAtual != null)
                    txtCodigoProduto.setText(produtoAtual.getDescricao());
            }
            if (produtoAtual == null) {
                JOptionPane.showMessageDialog(this, ConfigHelper.getProperty("error.notFound", "Produto"), "Atenção", JOptionPane.WARNING_MESSAGE);
                txtCodigoProduto.requestFocus();
                txtCodigoProduto.selectAll();
                return;
            }

            String preco = FunctionsHelper.numberFormat(produtoAtual.getVendaVista().doubleValue(), "#####0.00");
            lblNomeProduto.setText(produtoAtual.getDescricao());
            txtPreco.setText(preco);
            lblSubTotal.setText(preco);
            txtQuantidade.setText("1");
            txtQuantidade.requestFocus();
            txtQuantidade.selectAll();
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
            txtCodigoProduto.requestFocus();
            txtCodigoProduto.selectAll();
        }
    }//GEN-LAST:event_txtCodigoProdutoActionPerformed

    private void validarMoeda(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarMoeda
        SwingHelper.validarMoeda(evt);
    }//GEN-LAST:event_validarMoeda

    private void validarNumeroInteiro(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarNumeroInteiro
        SwingHelper.validarNumeroInteiro(evt);
    }//GEN-LAST:event_validarNumeroInteiro

    private void getKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getKey
        int tecla = evt.getKeyCode();
        int modificador = evt.getModifiers();
        if (tecla == KeyEvent.VK_ESCAPE) { // [Esc] Sair
            if (txtCodigoProduto.isFocusOwner()) {
                if (itens.size() > 0) {
                    btnCancelarVendaActionPerformed(null);
                }
                else {
                    dispose();
                }
            }
            else {
                limparCamposItem();
            }
        }
        else if (tecla == KeyEvent.VK_F5 && modificador == Event.CTRL_MASK) { // [Ctrl+F5] Finalizar Venda
            btnFinalizarVendaActionPerformed(null);
        }
        else if (tecla == KeyEvent.VK_DELETE && modificador == Event.CTRL_MASK) { // [Ctrl+Del] Extornar Item
            btnExtornarProdutoActionPerformed(null);
        }
        else if (tecla == KeyEvent.VK_F2) { // [F2] Digitar código do produto
            txtCodigoProduto.requestFocus();
            txtCodigoProduto.selectAll();
        }
        else if (tecla == KeyEvent.VK_F3) { // [F3] Alterar Preço
            txtPreco.requestFocus();
            txtPreco.selectAll();
        }
        else if (tecla == KeyEvent.VK_F4) { // [F4] Alterar quantidade
            txtQuantidade.requestFocus();
            txtQuantidade.selectAll();
        }
        else if (tecla == KeyEvent.VK_DELETE) { // [Del] Excluir item da lista
            int index = lstItens.getSelectedIndex();
            if (lstItens.isFocusOwner() && index != -1) {
                excluirItem(index);
            }
        }
    }//GEN-LAST:event_getKey

    private void btnCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVendaActionPerformed
        if (JOptionPane.showConfirmDialog(this, ConfigHelper.getProperty("warning.cancel", "Venda"), "Pergunta", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == 0) {
            iniciarVenda();
        }
    }//GEN-LAST:event_btnCancelarVendaActionPerformed

    private void btnExtornarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtornarProdutoActionPerformed
        lstItens.requestFocus();
        lstItens.setSelectedIndex(0);
    }//GEN-LAST:event_btnExtornarProdutoActionPerformed

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        venda.setItens(itens);
        FinalizarVenda fv = new FinalizarVenda(this, true, venda);
        fv.setVisible(true);
        fv.requestFocus();
        iniciarVenda();
    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnExtornarProduto;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblNumeroCaixa;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JList lstItens;
    private javax.swing.JPanel pnlTopo;
    private javax.swing.JScrollPane scrListaItens;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
