/*
 * PopupConsulta.java
 *
 * Created on 23 de Abril de 2007, 21:22
 */

package br.com.alphadev.contest.desktop;

import java.awt.event.KeyEvent;
import java.util.List;

import javax.swing.DefaultListModel;

import br.com.alphadev.util.ConfigHelper;

/**
 *
 * @author  Andre Penteado
 */
public class PopupConsulta extends javax.swing.JDialog {

    private static final long serialVersionUID = 3086686085544712575L;
    private List<? extends Object> opcoes = null;
    private Object result = null;

    /** Creates new form PopupConsulta */
    public PopupConsulta(java.awt.Frame parent, boolean modal, List<? extends Object> opcoes) {
        super(parent, modal);
        this.opcoes = opcoes;
        initComponents();
        lstLista.requestFocus();
        lstLista.setSelectedIndex(0);
    }

    public Object getResult() {
        return result;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrLista = new javax.swing.JScrollPane();
        lstLista = new javax.swing.JList();
        btnVoltar = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblCabecalho = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ConfigHelper.get().getString("sistema.nome") + " :: Selecione");
        setModal(true);

        lstLista.setFont(new java.awt.Font("Tahoma", 1, 12));
        DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < opcoes.size(); i++)
        dlm.addElement(opcoes.get(i).toString());
        lstLista.setModel(dlm);
        lstLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });
        scrLista.setViewportView(lstLista);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair_22x22.png"))); // NOI18N
        btnVoltar.setText("Voltar [Esc]");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnSelecionar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar_22x22.png"))); // NOI18N
        btnSelecionar.setText("Selecionar [Enter]");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCabecalho.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblCabecalho.setForeground(java.awt.Color.blue);
        lblCabecalho.setText("Selecione um dos itens abaixo");
        lblCabecalho.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.png"))); // NOI18N

        lblMensagem.setFont(new java.awt.Font("DejaVu Sans", 1, 10));
        lblMensagem.setForeground(java.awt.Color.red);
        lblMensagem.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblMensagem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .add(lblCabecalho, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblLogotipo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lblLogotipo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .add(lblCabecalho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblMensagem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, scrLista, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(btnSelecionar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnVoltar)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {btnSelecionar, btnVoltar}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(scrLista, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnVoltar)
                    .add(btnSelecionar))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {btnSelecionar, btnVoltar}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getKey
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ESCAPE) {
            btnVoltarActionPerformed(null);
        }
        else if (tecla == KeyEvent.VK_ENTER) {
            btnSelecionarActionPerformed(null);
        }
    }//GEN-LAST:event_getKey

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        result = opcoes.get(lstLista.getSelectedIndex());
        btnVoltarActionPerformed(evt);
    }//GEN-LAST:event_btnSelecionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JList lstLista;
    private javax.swing.JScrollPane scrLista;
    // End of variables declaration//GEN-END:variables

}
