/*
 * TotalVendidoCaixa.java
 *
 * Created on 26 de Julho de 2007, 21:12
 */

package br.com.alphadev.contest.desktop;

import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;

import br.com.alphadev.contest.services.VendaService;
import br.com.alphadev.core.ServicesFactory;
import br.com.alphadev.exception.ServiceValidationException;
import br.com.alphadev.util.ConfigHelper;
import br.com.alphadev.util.FunctionsHelper;
import br.com.alphadev.util.Log4jWrapper;
import br.com.alphadev.util.SwingHelper;

/**
 *
 * @author  andre
 */
public class TotalVendidoCaixa extends javax.swing.JFrame {

    private static final long serialVersionUID = -7628258120085378327L;
    private Log4jWrapper log = new Log4jWrapper(TotalVendidoCaixa.class, Login.getUserLogin());
    private VendaService vendaService = null;

    /** Creates new form TotalVendidoCaixa */
    public TotalVendidoCaixa() {
        try {
            if (Login.getUserLogin() == null) {
                throw new Exception(ConfigHelper.get().getString("error.accessDenied"));
            }
            vendaService = (VendaService)ServicesFactory.getInstance(VendaService.class, new Object[] { Login.getUserLogin() });
            initComponents();
        }
        catch (Exception ex) {
            log.fatal("AÇÕES NÃO INSTANCIADAS: ".concat(TotalVendidoCaixa.class.getName()), ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro desconhecido", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDataInicial = new javax.swing.JLabel();
        txtDataInicial = new javax.swing.JFormattedTextField();
        lblDataFinal = new javax.swing.JLabel();
        txtDataFinal = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        scrListagem = new javax.swing.JScrollPane();
        txtListagem = new javax.swing.JTextArea();
        lblTotal = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblCabecalho = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Total Vendido Por Caixa");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/logotipo.png")));

        lblDataInicial.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblDataInicial.setText("Data Inicial");

        txtDataInicial.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtDataInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        lblDataFinal.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblDataFinal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataFinal.setText("Data Final");

        txtDataFinal.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtDataFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_22x22.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        btnPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        txtListagem.setColumns(20);
        txtListagem.setEditable(false);
        txtListagem.setFont(new java.awt.Font("Courier New", 1, 18));
        txtListagem.setRows(5);
        txtListagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });
        scrListagem.setViewportView(txtListagem);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24));
        lblTotal.setForeground(java.awt.Color.blue);
        lblTotal.setText("R$ 0,00");

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair_22x22.png"))); // NOI18N
        btnVoltar.setText("Voltar [Esc]");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                getKey(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCabecalho.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        lblCabecalho.setForeground(java.awt.Color.blue);
        lblCabecalho.setText("Total Vendido no Caixa Por Período");
        lblCabecalho.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.png"))); // NOI18N

        lblMensagem.setFont(new java.awt.Font("DejaVu Sans", 1, 10));
        lblMensagem.setForeground(java.awt.Color.red);
        lblMensagem.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(
                                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblMensagem,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE).addComponent(lblCabecalho,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lblLogotipo).addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblLogotipo,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE).addGroup(
                        jPanel1Layout.createSequentialGroup().addComponent(lblCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup().addContainerGap().addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(scrListagem,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE).addGroup(
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup().addComponent(lblDataInicial).addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                                                                        txtDataInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(lblDataFinal).addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtDataFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 134,
                                                                                        Short.MAX_VALUE).addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(btnPesquisar))).addContainerGap()).addGroup(
                        layout.createSequentialGroup().addContainerGap().addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 422,
                                        Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnVoltar)
                                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                        layout.createSequentialGroup().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblDataInicial,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(txtDataFinal,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(btnPesquisar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(scrListagem,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE).addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(
                                                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(btnVoltar).addComponent(lblTotal)).addContainerGap()));

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { lblDataFinal, lblDataInicial, txtDataFinal, txtDataInicial });

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { btnVoltar, lblTotal });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            if (txtDataInicial.getText().equals("") || txtDataFinal.getText().equals("")) {
                log.debug(ConfigHelper.getProperty("error.required", "Campos de Data"));
                throw new ServiceValidationException(ConfigHelper.getProperty("error.required", "Campos de Data"));
            }

            List<Object[]> lista = vendaService.pesquisarTotalVendidoCaixaPorPeriodo(FunctionsHelper.stringToDate(txtDataInicial.getText()),
                            FunctionsHelper.stringToDate(txtDataFinal.getText()));
            StringBuilder sb = new StringBuilder();
            double total = 0;
            if (lista != null && lista.size() > 0) {
                for (int i = 0; i < lista.size(); i++) {
                    Object[] obj = lista.get(i);
                    double totalCaixa = (Double)obj[2];
                    total += totalCaixa;
                    sb.append(FunctionsHelper.fillSpacesRight(FunctionsHelper.dateFormat((Date)obj[0], "E dd/MM/yyyy"), 23));
                    sb.append(FunctionsHelper.fillSpacesRight((String)obj[1], 17));
                    sb.append(FunctionsHelper.fillSpacesLeft(FunctionsHelper.numberFormat((double)totalCaixa, "####0.00"), 8));
                    sb.append("\n");
                }
            }
            lblTotal.setText("R$ " + FunctionsHelper.numberFormat((double)total, "###,##0.00"));
            txtListagem.setText(sb.toString());
        }
        catch (ServiceValidationException sisex) {
            JOptionPane.showMessageDialog(this, sisex.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception ex) {
            log.error(ConfigHelper.get().getString("error.general"), ex);
            SwingHelper.exibeMensagemTemporaria(lblMensagem, ConfigHelper.get().getString("error.general"));
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void getKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_getKey
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_ESCAPE) {
            btnVoltarActionPerformed(null);
        }
        else if (tecla == KeyEvent.VK_ENTER) {
            btnPesquisarActionPerformed(null);
        }
    }//GEN-LAST:event_getKey

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblDataFinal;
    private javax.swing.JLabel lblDataInicial;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JScrollPane scrListagem;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    private javax.swing.JTextArea txtListagem;
    // End of variables declaration//GEN-END:variables
}
